- name: edit grub
  hosts: all
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: Grub edit
    replace:
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ item.option | regex_escape }}=).)*)(?:[" ]{{ item.option | regex_escape }}=\S+)?(.*")$'
      replace: '\1 {{ item.option }}={{ item.value }}\2'
    loop:
      - item1:
        option: net.ifnames
        value: 0
      - item2:
        option: biosdevname
        value: 0
