---
# tasks file for 003_vsftd
  - name: install vsftpd
    package: 
      name: "{{ item }}" 
      state: present
    with_items:
      - 'vsftpd'  

  - name: enable vsftpd
    service: 
      name: "{{ item }}"
      state: started 
      enabled: yes
    with_items:      
      - 'vsftpd'

  - name: config vsftpd with template
    vars:
      anonymous_enable: yes
      local_enable: yes
      write_enable: yes
      anon_upload_enable: yes
    template:
      src: vsftpd.j2
      dest: /etc/vsftpd/vsftpd.conf
    notify:
     - service restart

  - name: create readme file
    copy:
      content: "hello from ansible"
      dest: /var/ftp/pub/README
      force: no
      mode: 0444

  - name: open ftp-port
    firewalld:      
      service: ftp
      permanent: yes
      state: enabled
      immediate: yes
      
  - name: debug info
    ansible.builtin.debug:
      msg: "runs when you use debug"
    tags: [ never, debug ]
