---
# tasks file for 003_vsftd
  - name: install vsftpd
    package: 
      name: "{{ item }}" 
      state: present
    with_items:
      - 'vsftpd'
      - 'python3'

  - name: enable vsftpd
    service: 
      name: "{{ item }}"
      state: started 
      enabled: yes
    with_items:      
      - 'vsftpd'

 # - name: instal libsemanage-python
 #   pip:
 #    name: 
 #     - libsemanage-python
 #     - libselinux-python

  - name: create upload dir
    ansible.builtin.file:
      path: /var/ftp/pub/upload
      state: directory
      mode: '0755'

  - name: allow_ftpd_anon_write SELinux bool
    ansible.posix.seboolean:
      name: allow_ftpd_anon_write
      state: yes
      persistent: yes

  - name: config vsftpd with template
    vars:
      anonymous_enable: yes
      local_enable: yes
      write_enable: yes
      anon_upload_enable: yes
    template:
      src: vsftpd.j2
      dest: /etc/vsftpd/vsftpd.conf
    notify:
     - service restart  
    

  - name: create readme file
    copy:
      content: "hello from ansible"
      dest: /var/ftp/pub/README
      force: no
      mode: 0444

  - name: open ftp-port
    firewalld:      
      service: ftp
      permanent: yes
      state: enabled
      immediate: yes
      
  - name: debug info
    ansible.builtin.debug:
      msg: "runs when you use debug"
    tags: [ never, debug ]
